export declare const DIAMETER = 100;
export declare const ARC_WIDTH = 30;
export declare const START_ANGLE: number;
export declare const ARC_HOVER_WIDTH = 3;
export declare const CENTER_LABELS_ANGLE: number;
export declare const RADIUS: number;
export declare const LABEL_PADDING: number;
export declare const INNER_ARC_RADIUS: number;
export declare const MIN_COORDINATE_VALUE = 0.01;
export declare const MIN_VISIBLE_PERCENTS_VALUE = 2.8;
export declare const OVERLAP_DELTA = 2;
